### PR TITLE
fix(notification): surround with try/catch to avoid error with specif…

### PR DESCRIPTION
**Pull request by davinkevin**
…ic browser

Since Chrome 42 on Android (for example), the Notification API is present but can't be used directly.
We have to use serviceWorker to push notification to client instead of the simple window.Notification API. So, we have to catch the potential error and return nothing if an error occurs.
If you have a better idea of implementation, let me know.

### CODE REVIEW

**Comment by gregberge** [comment]
@davinkevin I don't know, but it's not possible to ignore errors juste like that, why don't put the try catch in your code?

**Comment by davinkevin** [comment]
I've done it in my current version of the code... 
https://github.com/davinkevin/Podcast-Server/blob/master/src/main/resources/static/app/js/modules/download/download.es6.js#L41

But I think the library should prevent the error to occurs, like you do when you check if the $window.Notification exists. It's why I've made this PR ;)

**Comment by gregberge** [comment]
@davinkevin I don't understand exactly when this error occurs, if we have `window.Notification`, the notification should work, isn't it?

**Comment by davinkevin** [comment]
It's occurs only on mobile device with the notification API available. 

The issue #10 is exactly what I try to solve by this PR.

**Comment by davinkevin** [comment]
I can also say the "try catch solution in my code" isn't good, because I have now multiple location where I create notification, so I have every time the 

``` js
try {
...
} catch (e) {}
```

instead of just calling the API of Angular-Notification.

Do you need more info, log, or anything else ? Everything is in the issue #10 and the [stackoverflow example](http://stackoverflow.com/questions/29774836/failed-to-construct-notification-illegal-constructor) related to it.

**Pull request merged**
